export const dummyProducts = [
  {
    id: 1,
    title: "Sony WH-1000XM5 Wireless Noise Canceling Headphones",
    price: 348.00,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&q=80",
    category: "Electronics",
    description: "Industry-leading noise cancellation with 30-hour battery life, crystal clear hands-free calling, and multipoint connection for seamless use across devices.",
  },
  {
    id: 2,
    title: "Apple Watch Series 9 (GPS, 41mm) Starlight Aluminum",
    price: 399.00,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800&q=80",
    category: "Accessories",
    description: "The most powerful Apple Watch yet, with the new S9 chip, Double Tap gesture, brighter display, and advanced health features.",
  },
  {
    id: 3,
    title: "Amazon Echo Dot (5th Gen) Smart Speaker with Alexa",
    price: 49.99,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1543512214-318c7553f230?w=800&q=80",
    category: "Electronics",
    description: "Our most popular smart speaker with a cleaner, bigger sound, a new temperature sensor, and a redesigned spherical shape.",
  },
  {
    id: 4,
    title: "Minimalist Genuine Leather Backpack",
    price: 120.00,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    category: "Fashion",
    description: "Hand-crafted from full-grain leather with a timeless design. Features a padded laptop compartment and multiple organizational pockets.",
  },
  {
    id: 5,
    title: "Premium Cotton Slim Fit Crew Neck T-Shirt",
    price: 25.00,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80",
    category: "Fashion",
    description: "Made from 100% organic Pima cotton, this ultra-soft tee offers a perfect slim fit with a classic crew neckline.",
  },
  {
    id: 6,
    title: "Classic Gold Plated Chronograph Watch",
    price: 155.00,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&q=80",
    category: "Accessories",
    description: "A timeless piece featuring a gold-plated stainless steel case, sapphire crystal glass, and Italian leather strap.",
  },
  {
    id: 7,
    title: "Samsung T7 Portable SSD 1TB - High-Speed External Drive",
    price: 119.99,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=800&q=80",
    category: "Electronics",
    description: "Transfer large files up to 2X faster with NVMe technology. Password protection with AES 256-bit hardware encryption.",
  },
  {
    id: 8,
    title: "Logitech MX Master 3S Wireless Performance Mouse",
    price: 99.00,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80",
    category: "Electronics",
    description: "Ergonomic masterpiece with 8000 DPI precision sensor, ultra-fast USB-C charging, and whisper-quiet clicks.",
  },
  {
    id: 9,
    title: "Scented Soy Wax Candle Gift Set - Lavender & Vanilla",
    price: 39.99,
    rating: 4.6,
    image: "https://images.pexels.com/photos/196658/pexels-photo-196658.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "Home",
    description: "A luxurious set of 3 hand-poured soy wax candles in premium glass jars. Long-lasting 60-hour burn time.",
  },
  {
    id: 10,
    title: "Premium Yoga Mat - Non-Slip, Eco-Friendly TPE",
    price: 65.00,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80",
    category: "Sports",
    description: "6mm thick eco-friendly TPE mat with superior cushioning, non-slip surface, and alignment lines for perfect positioning.",
  },
  {
    id: 11,
    title: "Ceramic Pour-Over Coffee Dripper Set",
    price: 48.00,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80",
    category: "Home",
    description: "Handcrafted ceramic pour-over dripper with stainless steel carafe, reusable filter, and a gooseneck kettle.",
  },
  {
    id: 12,
    title: "Women's Athletic Running Shoes - CloudFoam Comfort",
    price: 89.99,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    category: "Sports",
    description: "Lightweight running shoes with CloudFoam midsole for all-day comfort, breathable mesh upper, and durable rubber outsole.",
  },
  {
    id: 13,
    title: "Vitamin C Brightening Serum with Hyaluronic Acid",
    price: 32.00,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80",
    category: "Beauty",
    description: "20% Vitamin C + E + Ferulic Acid serum that visibly brightens skin, fades dark spots, and boosts collagen production.",
  },
  {
    id: 14,
    title: "Mechanical Keyboard - TKL RGB Backlit, Cherry MX Brown",
    price: 129.00,
    rating: 4.7,
    image: "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "Electronics",
    description: "Tenkeyless mechanical keyboard with Cherry MX Brown switches, per-key RGB lighting, and aircraft-grade aluminum frame.",
  },
  {
    id: 15,
    title: "Natural Wood Serving Charcuterie Board Set",
    price: 54.99,
    rating: 4.5,
    image: "https://images.pexels.com/photos/4109128/pexels-photo-4109128.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "Home",
    description: "Handcrafted acacia wood charcuterie board with integrated handles, juice grooves, and a set of 4 artisan knives.",
  },
  {
    id: 16,
    title: "Portable graytooth Speaker - Waterproof, 24H Battery",
    price: 79.99,
    rating: 4.6,
    image: "https://images.pexels.com/photos/1034653/pexels-photo-1034653.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "Electronics",
    description: "360-degree surround sound with deep bass, IP67 waterproof, dustproof, and shockproof for any adventure.",
  },
  {
    id: 17,
    title: "Men's Slim Fit Chino Pants - Stretch Comfort",
    price: 55.00,
    rating: 4.4,
    image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&q=80",
    category: "Fashion",
    description: "Modern slim-fit chinos with 4-way stretch fabric for ultimate comfort. Machine washable and wrinkle-resistant.",
  },
  {
    id: 18,
    title: "Stainless Steel Insulated Water Bottle 32oz",
    price: 34.99,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80",
    category: "Sports",
    description: "Triple-wall vacuum insulation keeps drinks cold 48 hours and hot 24 hours. BPA-free with a leak-proof lid.",
  },
  {
    id: 19,
    title: "Rose Gold Wireless Charging Pad - 15W Fast Charge",
    price: 29.99,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1591370874773-6702e8f12fd8?w=800&q=80",
    category: "Accessories",
    description: "Qi-certified 15W fast wireless charging pad compatible with all Qi-enabled devices. Ultra-slim and non-slip design.",
  },
  {
    id: 20,
    title: "Luxury Matte Lipstick Collection - 6 Shades",
    price: 42.00,
    rating: 4.7,
    image: "https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg?auto=compress&cs=tinysrgb&w=800",
    category: "Beauty",
    description: "Long-lasting matte finish lipstick set in 6 curated shades. Moisturizing formula with vitamin E and argan oil.",
  },
];
